### ISSUE TITLE
[STORY] Install Cal.com on prem along side existing calendar

### ISSUE THREAD

**Issue by chibenwa** [linagora/twake-calendar-side-service#152]
## Why ?

Cal.com eases meeting organisation drastically reducing the ping pong in order to schedule a meeting.

User can define availabilities that attendees can just pick: MAGIC.

Cal.com has a SaaS offer but also offers on-prem deployments (PG + Redis as a dependency)

License AGPL is compatible with LINAGORA AGPL

![Image](https://github.com/user-attachments/assets/1192fded-be65-4a32-9553-ed87ba35f1d3)

## What ?

Have a sample docker compose with cal.com pre-configured along side existing SPA.

## How ?

This is what ChatGPT says about it...

(Triple check needed...)

```
version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cal
      POSTGRES_PASSWORD: calpass
      POSTGRES_DB: caldb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  cal:
    image: calcom/cal.com:latest
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://cal:calpass@postgres:5432/caldb
      REDIS_URL: redis://redis:6379
      NEXTAUTH_URL: https://cal.localhost
      NEXTAUTH_SECRET: changeme123

      CALENDSO_ENCRYPTION_KEY: your_encryption_key_here
      ADMIN_EMAIL: admin@yourcompany.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: mdpadmin

      LDAP_URL: ldap://ldap-server
      LDAP_BIND_DN: cn=admin,dc=yourcompany,dc=com
      LDAP_BIND_CREDENTIALS: ldapadminpassword
      LDAP_SEARCH_BASE: ou=users,dc=yourcompany,dc=com
      LDAP_SEARCH_FILTER: (mail={{email}})

      SSO_PROVIDER: oidc
      OIDC_CLIENT_ID: calcom
      OIDC_CLIENT_SECRET: sso-secret
      OIDC_ISSUER: https://sso.yourcompany.com/realms/default

      VIDEO_CALL_PROVIDER: custom
      VIDEO_CALL_CUSTOM_URL: https://visio.yourcompany.com/{{event_id}}

    ports:
      - 3000:3000
    volumes:
      - ./cal-config:/app/config
    restart: always

volumes:
  postgres-data:
```
